### ISSUE TITLE
yangster sprotty only a single view?

### ISSUE THREAD

**Issue by jnorwood** [theia-ide/yang-eclipse#19]
I was testing the yangster  marketplace plugin.   Nice job with the sprotty diagram, but I was hoping to see a new diagram viewer open for each editor so I could compare diagrams side by side.  Is that in future plans?   I was testing on eclipse eclipse rap/rcp ide oxy v3 (eclipse-rcp-oxygen-3a-win32-x86_64.zip)  clean install on a x86-64 laptop.

**Comment by JanKoehnlein** [comment]
You can open any number of diagram views by choosing _Open in diagram_ either from the context menu of a _yang_ file in the navigator or hitting the button when such file is selected. Only the _generic_ diagram view _Window > Show view > Other... > YANG > Yang diagram_ will always show the current editor's model.

**Comment by jnorwood** [comment]
Thanks.  That is exactly what I was looking for.

There are some issues, though.  I get widget disposed pop-up errors every
time I click to switch focus between the two text editors.

I would also expect the outline view to switch focus if I click in a
diagram view, but it doesn't.

Anyway, this is a very nice operating diagram viewer, so I think I'll
continue working with it.

On Wed, May 9, 2018 02:06, Jan Koehnlein wrote:
You can open any number of diagram views by choosing _Open in diagram_
either from the context menu of a _yang_ file in the navigator or hitting
the button when such file is selected. Only the _generic_ diagram view
_Window > Show view > Other... > YANG > Yang diagram_ will always show the
current editor's model.

**Comment by jnorwood** [comment]
I was unable to recreate the issue with the switch focus pop-up errors today, so I'm going to close this.
I did notice something odd in yangster, that selection of root node in the diagram view requires double click while other nodes respond to single click.  Is that a feature?
