### ISSUE TITLE
marketplace install not working

### ISSUE THREAD

**Issue by anb0s** [theia-ide/yang-eclipse#20]
![image](https://user-images.githubusercontent.com/95811/40272131-e3fe27e4-5ba8-11e8-944c-1fb86e02086c.png)

**Comment by JanKoehnlein** [comment]
Sorry, that's most likely due to an outage of our build server. I just tried it and it works as expected.
Please try again now.

**Comment by mmews-n4** [comment]
Just checked and it is unavailable (see screenshot below). Also note that the website `https://theia-ide.github.io/yang-eclipse/repo` returns an 404.

<img width="371" alt="Screenshot 2019-10-10 at 10 44 12" src="https://user-images.githubusercontent.com/20560257/66553172-ee527780-eb4a-11e9-9787-e052ce8c2290.png">

**Comment by JanKoehnlein** [comment]
Should work again, thanks to @meysholdt restoring our Jenkins build.
