### ISSUE TITLE
Offline Plugin-Availability

### ISSUE THREAD

**Issue by pufferd-br** [theia-ide/yang-eclipse#21]
Hi,

Unfortunately our company firewall prohibits access to the Eclipse Marketplace - and the referenced update site (https://theia-ide.github.io/yang-eclipse/repo/) is invalid.
Could you please name the new URL so I could download the complete update-site for offline installation of your plugin?

Thank you and best regards,

David

**Comment by JanKoehnlein** [comment]
`https://theia-ide.github.io/yang-eclipse/repo/` refers to [our latest Jenkins build](http://services.typefox.io/open-source/jenkins/job/yang-eclipse/job/master/lastSuccessfulBuild/artifact/yang-eclipse/io.typefox.yang.eclipse.repository/target/repository). You can also download the entire [update-site as a zip](http://services.typefox.io/open-source/jenkins/job/yang-eclipse/job/master/lastSuccessfulBuild/artifact/yang-eclipse/io.typefox.yang.eclipse.repository/target/io.typefox.yang.eclipse.repository-0.2.0-SNAPSHOT.zip).

**Comment by pufferd-br** [comment]
Hello Jan,

The first link yields a 404 not found, the second link does not work - website is not sending data.

best,
david

**Comment by JanKoehnlein** [comment]
Hmmm, both links work fine on my machine, even when I am not logged into Jenkins. 
Could it be your firewall/proxy blocks it all? Maybe use https instead?
The zip is ~21 MB. Can I put it somewhere where you can pick it up?
